import {
  CustomerUser,
  Category,
  Store,
  Product,
  Review,
  Address,
  Coupon,
  Order,
  LiveTrackingData,
  WalletTransaction,
  NotificationItem,
  SupportTicket,
  DashboardSectionConfig,
  DeliveryContextData,
  SevazoPulseData,
} from '../types';

export const mockCustomer: CustomerUser = {
  id: 'cust-demo-1',
  name: 'Pradhyuman Saini',
  phone: '+91 98765 43210',
  email: 'pradhyuman@sevazo.in',
  avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200',
  isVerified: true,
  profileCompleted: true,
  totalSpent: 4280,
  ordersCount: 14,
  walletBalance: 350,
  loyaltyTier: 'GOLD',
  createdAt: new Date().toISOString(),
};

export const mockSevazoPulse: SevazoPulseData = {
  isActiveArea: true,
  areaName: 'Surya Nagar • Jaipur',
  productsAvailable: 247,
  storesOpen: 18,
  ridersNearby: 31,
  lastUpdated: 'Live right now',
};

export const mockDeliveryContext: DeliveryContextData = {
  etaMinutes: 18,
  availableItemsCount: 247,
  areaName: 'Home • Jaipur',
  badgeText: '⚡ Fast Delivery',
};

export const mockDashboardSections: DashboardSectionConfig[] = [
  { id: 'location_header', enabled: true, order: 1, title: 'Delivering to' },
  { id: 'search_bar', enabled: true, order: 2, title: 'Smart Search' },
  { id: 'active_order', enabled: true, order: 3, title: 'What is Arriving' },
  { id: 'sevazo_pulse', enabled: true, order: 4, title: 'Sevazo Pulse' },
  { id: 'category_rail', enabled: true, order: 5, title: 'Shop by Category' },
  { id: 'hero_banner', enabled: true, order: 6, title: 'Personalized Hero' },
  { id: 'buy_again', enabled: true, order: 7, title: 'Buy Again', subtitle: 'Frequently ordered items' },
  { id: 'available_now', enabled: true, order: 8, title: '⚡ Available Near You', subtitle: 'Delivered in ~15 mins' },
  { id: 'smart_basket', enabled: true, order: 9, title: 'Smart Basket' },
  { id: 'stores_nearby', enabled: true, order: 10, title: '🏪 Stores Around You', subtitle: 'Direct from neighborhood merchants' },
  { id: 'trending', enabled: true, order: 11, title: '🔥 Trending in Your Area', subtitle: 'What people are buying right now' },
  { id: 'deals', enabled: true, order: 12, title: '🏷️ Deals You\'ll Love', subtitle: 'Limited-time price drops' },
  { id: 'picked_for_you', enabled: true, order: 13, title: '✨ Picked for You', subtitle: 'Based on your taste & habits' },
  { id: 'recently_viewed', enabled: true, order: 14, title: '🛍️ Recently Viewed', subtitle: 'Jump back to items you liked' },
];

export const mockBanners = [
  {
    id: 'b-1',
    title: 'Fresh Picks For You',
    subtitle: 'Up to 30% OFF on organic harvest & fresh dairy',
    tag: '⚡ 15 MIN DELIVERY',
    bgColor: '#059669',
    imageUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=600',
    ctaText: 'Shop Now',
  },
  {
    id: 'b-2',
    title: 'Midnight Munchies & Treats',
    subtitle: 'Artisan chips, gourmet dips, and gelato delivered fast',
    tag: '🔥 FLAT 40% OFF',
    bgColor: '#4F46E5',
    imageUrl: 'https://images.unsplash.com/photo-1509722747041-616f39b57569?w=600',
    ctaText: 'Explore',
  },
  {
    id: 'b-3',
    title: 'Neighborhood Wellness Hub',
    subtitle: 'Prescriptions, immunity boosters & wellness within 20 mins',
    tag: '💊 PHARMACY EXPRESS',
    bgColor: '#0891B2',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600',
    ctaText: 'Order Now',
  },
];

export const mockCategories: Category[] = [
  {
    id: 'cat-grocery',
    name: 'Grocery',
    slug: 'grocery',
    icon: '🥦',
    imageUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=200',
    itemCount: 420,
  },
  {
    id: 'cat-fresh',
    name: 'Fresh Fruits',
    slug: 'fruits-vegetables',
    icon: '🍎',
    imageUrl: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=200',
    itemCount: 180,
  },
  {
    id: 'cat-food',
    name: 'Food & Snacks',
    slug: 'food-snacks',
    icon: '🍕',
    imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=200',
    itemCount: 290,
  },
  {
    id: 'cat-pharmacy',
    name: 'Pharmacy',
    slug: 'pharmacy',
    icon: '💊',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=200',
    itemCount: 140,
  },
  {
    id: 'cat-electronics',
    name: 'Electronics',
    slug: 'electronics',
    icon: '📱',
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=200',
    itemCount: 95,
  },
  {
    id: 'cat-fashion',
    name: 'Fashion',
    slug: 'fashion',
    icon: '👕',
    imageUrl: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=200',
    itemCount: 160,
  },
  {
    id: 'cat-beauty',
    name: 'Beauty',
    slug: 'beauty',
    icon: '💄',
    imageUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=200',
    itemCount: 110,
  },
  {
    id: 'cat-home',
    name: 'Home & Living',
    slug: 'home-living',
    icon: '🏠',
    imageUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=200',
    itemCount: 130,
  },
  {
    id: 'cat-services',
    name: 'Services',
    slug: 'local-services',
    icon: '🔧',
    imageUrl: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=200',
    itemCount: 45,
  },
];

export const mockBestsellerQuadCategories = [
  {
    id: 'cat-fresh',
    name: 'Vegetables & Fruits',
    moreCountText: '+215 more',
    images: [
      'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=150', // Potatoes
      'https://images.unsplash.com/photo-1508747703725-719777637510?w=150', // Red Onions
      'https://images.unsplash.com/photo-1588252303782-cb80119abd6d?w=150', // Green Chillies
      'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=150', // Spinach / Coriander
    ],
  },
  {
    id: 'cat-dairy',
    name: 'Dairy, Bread & Eggs',
    moreCountText: '+29 more',
    images: [
      'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=150', // Milk pouch
      'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=150', // Dahi / Curd
      'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=150', // Bread loaf
      'https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=150', // Eggs
    ],
  },
  {
    id: 'cat-beverages',
    name: 'Cold Drinks & Juices',
    moreCountText: '+256 more',
    images: [
      'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=150', // Green Soda Bottle
      'https://images.unsplash.com/photo-1554866585-cd94860890b7?w=150', // Cola Bottle
      'https://images.unsplash.com/photo-1629203851122-3726ecdf080e?w=150', // Drink Cans Pack
      'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=150', // Juice Bottle
    ],
  },
  {
    id: 'cat-chips',
    name: 'Chips & Namkeen',
    moreCountText: '+566 more',
    images: [
      'https://images.unsplash.com/photo-1621447504864-d8686e12698c?w=150', // Kurkure / Namkeen
      'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=150', // Potato chips
      'https://images.unsplash.com/photo-1613919113640-25732ec5e61f?w=150', // Uncle Chipps
      'https://images.unsplash.com/photo-1599490659213-e2b9527bd087?w=150', // Crisps
    ],
  },
  {
    id: 'cat-staples',
    name: 'Cooking Oil & Ghee',
    moreCountText: '+353 more',
    images: [
      'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=150', // Cooking Oil
      'https://images.unsplash.com/photo-1589927986089-35812388d1f4?w=150', // Fortune Oil
      'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=150', // Atta / Flour
      'https://images.unsplash.com/photo-1596560548464-f010549b84d7?w=150', // Rice
    ],
  },
  {
    id: 'cat-bakery',
    name: 'Bakery & Biscuits',
    moreCountText: '+276 more',
    images: [
      'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=150', // Biscuits
      'https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?w=150', // Cookies
      'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=150', // Dark Chocolate
      'https://images.unsplash.com/photo-1587248720327-8eb72564be1e?w=150', // Sweet treats
    ],
  },
  {
    id: 'cat-beauty',
    name: 'Beauty & Personal Care',
    moreCountText: '+184 more',
    images: [
      'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=150', // Skincare cream
      'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=150', // Shampoo
      'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=150', // Lotion
      'https://images.unsplash.com/photo-1608248597359-0091815e4785?w=150', // Serum
    ],
  },
  {
    id: 'cat-pharmacy',
    name: 'Pharmacy & Wellness',
    moreCountText: '+92 more',
    images: [
      'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=150', // Pills
      'https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?w=150', // Capsules
      'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=150', // First aid
      'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=150', // Wellness bottle
    ],
  },
  {
    id: 'cat-electronics',
    name: 'Electronics & Gadgets',
    moreCountText: '+140 more',
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=150', // Headphones
      'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=150', // Earbuds
      'https://images.unsplash.com/photo-1609081219090-a6d8173087ec?w=150', // Smart watch
      'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=150', // Power bank
    ],
  },
  {
    id: 'cat-cleaning',
    name: 'Home & Cleaning',
    moreCountText: '+210 more',
    images: [
      'https://images.unsplash.com/photo-1585421514738-01798e348b17?w=150', // Cleaning spray
      'https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=150', // Detergent
      'https://images.unsplash.com/photo-1563453392212-326f5e854473?w=150', // Hand wash
      'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=150', // Tissues
    ],
  },
  {
    id: 'cat-instant',
    name: 'Instant & Frozen Food',
    moreCountText: '+165 more',
    images: [
      'https://images.unsplash.com/photo-1612927601601-6638404737ce?w=150', // Noodles
      'https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?w=150', // French fries
      'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=150', // Pasta
      'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=150', // Frozen veg
    ],
  },
];

export const mockStores: Store[] = [
  {
    id: 'store-1',
    businessName: 'SevaZo Supermart Express',
    ownerName: 'Ramesh Sharma',
    avatar: 'https://images.unsplash.com/photo-1534723452862-4c874018d66d?w=150',
    coverImage: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=600',
    rating: 4.9,
    reviewsCount: 1420,
    deliveryTime: '12-15 min',
    distanceKm: 0.9,
    address: 'Plot 42, Malviya Nagar, Jaipur',
    city: 'Jaipur',
    isOpen: true,
    tags: ['Groceries', 'Dairy', 'Snacks', 'Beverages'],
    bannerText: '⚡ Top Rated Neighborhood Store',
  },
  {
    id: 'store-2',
    businessName: 'Apollo 24/7 Pharmacy Express',
    ownerName: 'Dr. Sunita Gupta',
    avatar: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=150',
    coverImage: 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=600',
    rating: 4.8,
    reviewsCount: 890,
    deliveryTime: '15-20 min',
    distanceKm: 1.4,
    address: 'B-12, Vaishali Nagar, Jaipur',
    city: 'Jaipur',
    isOpen: true,
    tags: ['Medicines', 'Wellness', 'Baby Care', 'Personal Hygiene'],
    bannerText: '🩺 Verified Licensed Pharmacists',
  },
  {
    id: 'store-3',
    businessName: 'Fresh Harvest Farms Direct',
    ownerName: 'Vikram Singh',
    avatar: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=150',
    coverImage: 'https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=600',
    rating: 4.9,
    reviewsCount: 654,
    deliveryTime: '10-14 min',
    distanceKm: 0.6,
    address: 'C-Scheme Market, Jaipur',
    city: 'Jaipur',
    isOpen: true,
    tags: ['Hydroponics', 'Organic Veggies', 'Imported Fruits'],
    bannerText: '🌱 Harvested Within 4 Hours',
  },
  {
    id: 'store-4',
    businessName: 'Bakehouse Artisan Bakery',
    ownerName: 'Chef Aditi Ray',
    avatar: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=150',
    coverImage: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600',
    rating: 4.7,
    reviewsCount: 420,
    deliveryTime: '20-25 min',
    distanceKm: 2.1,
    address: 'Tonk Road, Jaipur',
    city: 'Jaipur',
    isOpen: true,
    tags: ['Sourdough', 'Croissants', 'Cakes', 'Desserts'],
    bannerText: '🥐 Freshly Baked Batches',
  },
];

// 🔄 "Buy Again" Products (Staples for quick 1-tap reorder)
export const mockBuyAgainProducts: Product[] = [
  {
    id: 'ba-1',
    name: 'Amul Taaza Fresh Toned Milk',
    slug: 'amul-taaza-fresh-toned-milk',
    description: 'Fresh pasteurised toned milk with essential vitamins.',
    categoryId: 'cat-grocery',
    categoryName: 'Dairy',
    vendorId: 'store-1',
    storeId: 'store-1',
    storeName: 'SevaZo Supermart Express',
    price: 54,
    compareAtPrice: 56,
    discountPercent: 4,
    stock: 80,
    unit: '1 Litre',
    rating: 4.9,
    reviewsCount: 3200,
    images: ['https://pngimg.com/d/milk_PNG12739.png'],
    tags: ['Milk', 'Daily Essential', 'Dairy'],
    isFeatured: true,
    inStock: true,
  },
  {
    id: 'ba-2',
    name: 'Harvest Gold 100% Whole Wheat Bread',
    slug: 'harvest-gold-whole-wheat-bread',
    description: 'Freshly baked nutritious whole wheat brown bread loaf.',
    categoryId: 'cat-grocery',
    categoryName: 'Bakery',
    vendorId: 'store-1',
    storeId: 'store-1',
    storeName: 'SevaZo Supermart Express',
    price: 45,
    compareAtPrice: 50,
    discountPercent: 10,
    stock: 45,
    unit: '400 g',
    rating: 4.8,
    reviewsCount: 1450,
    images: ['https://pngimg.com/d/bread_PNG2300.png'],
    tags: ['Bread', 'Breakfast'],
    inStock: true,
  },
  {
    id: 'ba-3',
    name: 'Farm Fresh Brown Eggs (Pack of 6)',
    slug: 'farm-fresh-brown-eggs-6',
    description: 'Nutrient-rich, protein-packed vegetarian feed brown eggs.',
    categoryId: 'cat-grocery',
    categoryName: 'Eggs',
    vendorId: 'store-1',
    storeId: 'store-1',
    storeName: 'SevaZo Supermart Express',
    price: 68,
    compareAtPrice: 80,
    discountPercent: 15,
    stock: 60,
    unit: '6 Pieces',
    rating: 4.9,
    reviewsCount: 920,
    images: ['https://pngimg.com/d/egg_PNG40784.png'],
    tags: ['Eggs', 'High Protein'],
    inStock: true,
  },
  {
    id: 'ba-4',
    name: 'Daawat Rozana Super Basmati Rice',
    slug: 'daawat-rozana-super-basmati-rice',
    description: 'Aromatic long-grain basmati rice perfect for daily meals.',
    categoryId: 'cat-grocery',
    categoryName: 'Grocery',
    vendorId: 'store-1',
    storeId: 'store-1',
    storeName: 'SevaZo Supermart Express',
    price: 110,
    compareAtPrice: 145,
    discountPercent: 24,
    stock: 35,
    unit: '1 kg',
    rating: 4.7,
    reviewsCount: 680,
    images: ['https://pngimg.com/d/corn_PNG5275.png'],
    tags: ['Rice', 'Staples'],
    inStock: true,
  },
  {
    id: 'ba-5',
    name: 'Dove Beauty Moisture Bathing Bar',
    slug: 'dove-beauty-moisture-bathing-bar',
    description: 'Contains 1/4 moisturising cream for soft, smooth glowing skin.',
    categoryId: 'cat-beauty',
    categoryName: 'Beauty',
    vendorId: 'store-1',
    storeId: 'store-1',
    storeName: 'SevaZo Supermart Express',
    price: 62,
    compareAtPrice: 75,
    discountPercent: 17,
    stock: 50,
    unit: '100 g',
    rating: 4.8,
    reviewsCount: 1100,
    images: ['https://pngimg.com/d/soap_PNG65.png'],
    tags: ['Soap', 'Personal Care'],
    inStock: true,
  },
  {
    id: 'ba-6',
    name: 'Fresh Robusta Bananas (Kela)',
    slug: 'fresh-robusta-bananas',
    description: 'Naturally ripened, sweet and potassium-rich yellow bananas.',
    categoryId: 'cat-fresh',
    categoryName: 'Fresh Fruits',
    vendorId: 'store-3',
    storeId: 'store-3',
    storeName: 'Fresh Harvest Farms Direct',
    price: 42,
    compareAtPrice: 55,
    discountPercent: 23,
    stock: 90,
    unit: '1 kg (5-6 pcs)',
    rating: 4.8,
    reviewsCount: 2100,
    images: ['https://pngimg.com/d/banana_PNG842.png'],
    tags: ['Fruits', 'Fresh'],
    inStock: true,
  },
];

// ⚡ "Available Near You" Products (Ultra fast delivery items)
export const mockAvailableNowProducts: Product[] = [
  {
    id: 'an-1',
    name: 'Hydroponic English Spinach (Palak)',
    slug: 'hydroponic-english-spinach',
    description: 'Crisp, washed, pesticide-free fresh hydroponic palak leaves.',
    categoryId: 'cat-fresh',
    categoryName: 'Fresh Produce',
    vendorId: 'store-3',
    storeId: 'store-3',
    storeName: 'Fresh Harvest Farms Direct',
    price: 36,
    compareAtPrice: 50,
    discountPercent: 28,
    stock: 40,
    unit: '250 g',
    rating: 4.9,
    reviewsCount: 540,
    images: ['https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=500'],
    tags: ['Spinach', 'Green Veggies', 'Organic'],
    isFeatured: true,
    inStock: true,
  },
  {
    id: 'an-2',
    name: 'Amul Pasteurised Salted Butter',
    slug: 'amul-pasteurised-salted-butter',
    description: 'Utterly butterly delicious creamy table butter.',
    categoryId: 'cat-grocery',
    categoryName: 'Dairy',
    vendorId: 'store-1',
    storeId: 'store-1',
    storeName: 'SevaZo Supermart Express',
    price: 58,
    compareAtPrice: 60,
    discountPercent: 3,
    stock: 65,
    unit: '100 g',
    rating: 4.9,
    reviewsCount: 4100,
    images: ['https://pngimg.com/d/cheese_PNG25301.png'],
    tags: ['Butter', 'Dairy', 'Breakfast'],
    inStock: true,
  },
  {
    id: 'an-3',
    name: 'Crisp Shimla Royal Red Apples',
    slug: 'shimla-royal-red-apples',
    description: 'Juicy, sweet, crunch-loaded orchard handpicked apples.',
    categoryId: 'cat-fresh',
    categoryName: 'Fresh Fruits',
    vendorId: 'store-3',
    storeId: 'store-3',
    storeName: 'Fresh Harvest Farms Direct',
    price: 135,
    compareAtPrice: 175,
    discountPercent: 22,
    stock: 55,
    unit: '1 kg',
    rating: 4.8,
    reviewsCount: 890,
    images: ['https://pngimg.com/d/apple_PNG12405.png'],
    tags: ['Apples', 'Fruits', 'Immunity'],
    inStock: true,
  },
  {
    id: 'an-4',
    name: 'Coca-Cola Zero Sugar Soft Drink',
    slug: 'coca-cola-zero-sugar-soft-drink',
    description: 'Classic refreshing Coca-Cola taste with zero calories and sugar.',
    categoryId: 'cat-food',
    categoryName: 'Food & Snacks',
    vendorId: 'store-1',
    storeId: 'store-1',
    storeName: 'SevaZo Supermart Express',
    price: 40,
    compareAtPrice: 40,
    discountPercent: 0,
    stock: 120,
    unit: '300 ml Can',
    rating: 4.8,
    reviewsCount: 1640,
    images: ['https://pngimg.com/d/coca_cola_PNG8913.png'],
    tags: ['Beverages', 'Cold Drink'],
    inStock: true,
  },
  {
    id: 'an-5',
    name: 'Lay\'s India\'s Magic Masala Chips',
    slug: 'lays-indias-magic-masala-chips',
    description: 'Crisp potato chips seasoned with authentic Indian spices.',
    categoryId: 'cat-food',
    categoryName: 'Food & Snacks',
    vendorId: 'store-1',
    storeId: 'store-1',
    storeName: 'SevaZo Supermart Express',
    price: 20,
    compareAtPrice: 20,
    discountPercent: 0,
    stock: 150,
    unit: '50 g',
    rating: 4.7,
    reviewsCount: 2800,
    images: ['https://pngimg.com/d/potato_chips_PNG42.png'],
    tags: ['Snacks', 'Chips'],
    inStock: true,
  },
];

// 🔥 "Trending in Your Area" Products
export const mockTrendingProducts: Product[] = [
  {
    id: 'tr-1',
    name: 'Ripe Hass Avocado (Imported)',
    slug: 'ripe-hass-avocado-imported',
    description: 'Creamy, rich in healthy fats, perfect for guacamole and toast.',
    categoryId: 'cat-fresh',
    categoryName: 'Fresh Fruits',
    vendorId: 'store-3',
    storeId: 'store-3',
    storeName: 'Fresh Harvest Farms Direct',
    price: 189,
    compareAtPrice: 240,
    discountPercent: 21,
    stock: 35,
    unit: '1 piece (200 g)',
    rating: 4.9,
    reviewsCount: 710,
    images: ['https://pngimg.com/d/avocado_PNG15500.png'],
    tags: ['Superfood', 'Avocado', 'Trending'],
    isTrending: true,
    inStock: true,
  },
  {
    id: 'tr-2',
    name: 'Figaro Extra Virgin Olive Oil',
    slug: 'figaro-extra-virgin-olive-oil',
    description: 'Pure cold-extracted Spanish olive oil for healthy culinary cooking.',
    categoryId: 'cat-grocery',
    categoryName: 'Cooking Essentials',
    vendorId: 'store-1',
    storeId: 'store-1',
    storeName: 'SevaZo Supermart Express',
    price: 649,
    compareAtPrice: 799,
    discountPercent: 19,
    stock: 25,
    unit: '500 ml',
    rating: 4.9,
    reviewsCount: 1420,
    images: ['https://pngimg.com/d/olive_oil_PNG9.png'],
    tags: ['Olive Oil', 'Healthy Cooking'],
    isTrending: true,
    inStock: true,
  },
  {
    id: 'tr-3',
    name: 'California Jumbo Almonds (Badam)',
    slug: 'california-jumbo-almonds',
    description: '100% natural, vacuum-packed raw crunchy California almonds.',
    categoryId: 'cat-grocery',
    categoryName: 'Dry Fruits',
    vendorId: 'store-1',
    storeId: 'store-1',
    storeName: 'SevaZo Supermart Express',
    price: 249,
    compareAtPrice: 320,
    discountPercent: 22,
    stock: 40,
    unit: '250 g',
    rating: 4.8,
    reviewsCount: 980,
    images: ['https://pngimg.com/d/almond_PNG75.png'],
    tags: ['Dry Fruits', 'Healthy Snack'],
    isTrending: true,
    inStock: true,
    backInStock: true,
  },
  {
    id: 'tr-4',
    name: 'Wipro Smart LED 9W RGB Bulb',
    slug: 'wipro-smart-led-9w-rgb-bulb',
    description: '16 Million colors with WiFi voice control via Alexa & Google Assistant.',
    categoryId: 'cat-electronics',
    categoryName: 'Electronics',
    vendorId: 'store-1',
    storeId: 'store-1',
    storeName: 'SevaZo Supermart Express',
    price: 499,
    compareAtPrice: 899,
    discountPercent: 44,
    stock: 30,
    unit: '1 unit',
    rating: 4.6,
    reviewsCount: 520,
    images: ['https://pngimg.com/d/bulb_PNG1243.png'],
    tags: ['Smart Home', 'Electronics', 'Lighting'],
    isTrending: true,
    inStock: true,
    warranty: '1 Year Warranty',
    priceDrop: 50,
  },
];

// 🏷️ "Deals You'll Love" Products (High discounts)
export const mockDealProducts: Product[] = [
  {
    id: 'dl-1',
    name: 'Cadbury Celebrations Premium Gift Pack',
    slug: 'cadbury-celebrations-premium-gift-pack',
    description: 'Assorted rich chocolates including Dairy Milk, 5 Star & Gems.',
    categoryId: 'cat-food',
    categoryName: 'Chocolates & Sweets',
    vendorId: 'store-1',
    storeId: 'store-1',
    storeName: 'SevaZo Supermart Express',
    price: 150,
    compareAtPrice: 300,
    discountPercent: 50,
    stock: 60,
    unit: '280 g Pack',
    rating: 4.9,
    reviewsCount: 3100,
    images: ['https://pngimg.com/d/chocolate_PNG12.png'],
    tags: ['Chocolates', '50% OFF', 'Flash Deal'],
    isFeatured: true,
    inStock: true,
  },
  {
    id: 'dl-2',
    name: 'Nescafe Gold Blend Premium Coffee',
    slug: 'nescafe-gold-blend-premium-coffee',
    description: 'Finest golden roasted Arabica & Robusta beans for a smooth aroma.',
    categoryId: 'cat-grocery',
    categoryName: 'Beverages',
    vendorId: 'store-1',
    storeId: 'store-1',
    storeName: 'SevaZo Supermart Express',
    price: 360,
    compareAtPrice: 580,
    discountPercent: 38,
    stock: 28,
    unit: '100 g Glass Jar',
    rating: 4.8,
    reviewsCount: 1650,
    images: ['https://pngimg.com/d/coffee_beans_PNG9273.png'],
    tags: ['Coffee', 'Mega Deal'],
    inStock: true,
  },
  {
    id: 'dl-3',
    name: 'Artisan Golden Butter Croissants (Set of 2)',
    slug: 'artisan-golden-butter-croissants',
    description: 'Flaky French pastry layered with rich butter, baked every morning.',
    categoryId: 'cat-food',
    categoryName: 'Bakery',
    vendorId: 'store-4',
    storeId: 'store-4',
    storeName: 'Bakehouse Artisan Bakery',
    price: 110,
    compareAtPrice: 160,
    discountPercent: 31,
    stock: 20,
    unit: '2 Pieces',
    rating: 4.9,
    reviewsCount: 480,
    images: ['https://pngimg.com/d/croissant_PNG46.png'],
    tags: ['Bakery', 'Breakfast', 'Deal'],
    inStock: true,
  },
  {
    id: 'dl-4',
    name: 'Raw Pressery Valencia Orange Juice',
    slug: 'raw-pressery-valencia-orange-juice',
    description: '100% pure Valencia oranges, cold-pressed with zero added sugar.',
    categoryId: 'cat-grocery',
    categoryName: 'Beverages',
    vendorId: 'store-1',
    storeId: 'store-1',
    storeName: 'SevaZo Supermart Express',
    price: 180,
    compareAtPrice: 360,
    discountPercent: 50,
    discountBadge: 'Buy 1 Get 1 FREE',
    stock: 40,
    unit: '2 x 250 ml (B1G1)',
    rating: 4.8,
    reviewsCount: 920,
    images: ['https://pngimg.com/d/orange_juice_PNG779.png'],
    tags: ['Juice', 'B1G1', 'Deal', 'Cold Pressed'],
    inStock: true,
    deliveryEtaMinutes: 14,
  },
];

// ✨ "Picked for You" (Personalized algorithm suggestions)
export const mockRecommendedProducts: Product[] = [
  {
    id: 'rec-1',
    name: 'Organic Greek Yogurt with Wild Blueberries',
    slug: 'organic-greek-yogurt-wild-blueberries',
    description: 'Thick, creamy high-protein Greek yogurt with whole crushed blueberries.',
    categoryId: 'cat-grocery',
    categoryName: 'Dairy',
    vendorId: 'store-1',
    storeId: 'store-1',
    storeName: 'SevaZo Supermart Express',
    price: 75,
    compareAtPrice: 95,
    discountPercent: 21,
    stock: 35,
    unit: '120 g Cup',
    rating: 4.9,
    reviewsCount: 820,
    images: ['https://pngimg.com/d/cheese_PNG25313.png'],
    tags: ['Yogurt', 'High Protein', 'Healthy'],
    inStock: true,
  },
  {
    id: 'rec-2',
    name: 'Pure Sourdough Country Loaf (Eggless)',
    slug: 'pure-sourdough-country-loaf',
    description: 'Fermented naturally for 36 hours for rich flavour and gut health.',
    categoryId: 'cat-food',
    categoryName: 'Bakery',
    vendorId: 'store-4',
    storeId: 'store-4',
    storeName: 'Bakehouse Artisan Bakery',
    price: 140,
    compareAtPrice: 180,
    discountPercent: 22,
    stock: 18,
    unit: '450 g',
    rating: 4.9,
    reviewsCount: 610,
    images: ['https://pngimg.com/d/bread_PNG2280.png'],
    tags: ['Sourdough', 'Artisan Bakery'],
    inStock: true,
  },
  {
    id: 'rec-3',
    name: 'Dettol Original Germ Protection Liquid Handwash',
    slug: 'dettol-original-handwash-refill',
    description: '100% better protection from illness-causing germs.',
    categoryId: 'cat-beauty',
    categoryName: 'Personal Care',
    vendorId: 'store-1',
    storeId: 'store-1',
    storeName: 'SevaZo Supermart Express',
    price: 99,
    compareAtPrice: 125,
    discountPercent: 20,
    stock: 70,
    unit: '675 ml Refill',
    rating: 4.8,
    reviewsCount: 1900,
    images: ['https://pngimg.com/d/bottle_PNG2091.png'],
    tags: ['Hygiene', 'Handwash'],
    inStock: true,
  },
];

// 🛍️ "Recently Viewed" Products
export const mockRecentlyViewedProducts: Product[] = [
  mockBuyAgainProducts[0],
  mockTrendingProducts[0],
  mockAvailableNowProducts[0],
  mockDealProducts[0],
];

// All mock products master array
export const mockProducts: Product[] = [
  ...mockBuyAgainProducts,
  ...mockAvailableNowProducts,
  ...mockTrendingProducts,
  ...mockDealProducts,
  ...mockRecommendedProducts,
];

// Sample active in-transit order for the live tracking widget
export const mockActiveOrder: Order = {
  id: 'order-active-101',
  orderNumber: 'SZ-9042',
  createdAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
  status: 'IN_TRANSIT',
  paymentStatus: 'PAID',
  paymentMethod: 'UPI',
  items: [
    {
      id: 'item-1',
      productId: 'ba-1',
      productName: 'Amul Taaza Fresh Toned Milk',
      productImage: 'https://pngimg.com/d/milk_PNG12739.png',
      unitPrice: 54,
      quantity: 2,
      totalPrice: 108,
    },
    {
      id: 'item-2',
      productId: 'ba-2',
      productName: 'Harvest Gold 100% Whole Wheat Bread',
      productImage: 'https://pngimg.com/d/bread_PNG2300.png',
      unitPrice: 45,
      quantity: 1,
      totalPrice: 45,
    },
  ],
  subtotal: 153,
  deliveryFee: 15,
  tax: 5,
  discount: 0,
  totalAmount: 173,
  deliveryAddress: {
    id: 'addr-1',
    label: 'Home',
    line1: 'B-44, Surya Nagar, Gopalpura Bypass',
    city: 'Jaipur',
    state: 'Rajasthan',
    pincode: '302015',
    isDefault: true,
  },
  store: {
    id: 'store-1',
    businessName: 'SevaZo Supermart Express',
    phone: '+91 80000 12345',
  },
  estimatedDeliveryTime: 'Arriving in ~8 mins',
  deliveryOtp: '4829',
  rider: {
    id: 'rider-55',
    name: 'Suresh Kumar',
    phone: '+91 98765 00112',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=120',
    rating: 4.9,
    vehicleNumber: 'RJ 14 EX 9021',
    vehicleType: 'Electric Scooter',
  },
  canCancel: false,
  canReturn: false,
};

export const mockReviews: Review[] = [];
export const mockAddresses: Address[] = [
  {
    id: 'addr-1',
    label: 'Home',
    line1: 'B-44, Surya Nagar, Gopalpura Bypass',
    city: 'Jaipur',
    state: 'Rajasthan',
    pincode: '302015',
    isDefault: true,
  },
  {
    id: 'addr-2',
    label: 'Work',
    line1: 'Tower 4, World Trade Park, JLN Marg',
    city: 'Jaipur',
    state: 'Rajasthan',
    pincode: '302017',
    isDefault: false,
  },
];

export const mockCoupons: Coupon[] = [
  {
    id: 'c-1',
    code: 'SEVAZO50',
    description: 'Flat 50% OFF up to ₹100 on orders above ₹199',
    discountType: 'PERCENTAGE',
    discountValue: 50,
    minOrderAmount: 199,
    maxDiscount: 100,
    validUntil: '2026-12-31',
    isActive: true,
  },
  {
    id: 'c-2',
    code: 'FREESHIP',
    description: 'Free delivery on all neighborhood store orders',
    discountType: 'FIXED',
    discountValue: 25,
    minOrderAmount: 99,
    validUntil: '2026-12-31',
    isActive: true,
  },
];

export const mockOrders: Order[] = [mockActiveOrder];
export const mockLiveTracking: LiveTrackingData | null = null as any;
export const mockNotifications: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'Order Arriving in 12 min 🛵',
    message: 'Rider Suresh Kumar is on his way with your order #SZ-9042 from SevaZo Supermart.',
    type: 'ORDER',
    isRead: false,
    timestamp: 'Just now',
  },
  {
    id: 'notif-2',
    title: 'Price Dropped by ₹50! ❤️',
    message: 'Sony Wireless Headphones in your wishlist dropped by ₹50! Now only ₹24,940.',
    type: 'WISHLIST',
    isRead: false,
    timestamp: '15 min ago',
  },
  {
    id: 'notif-3',
    title: '20% OFF on FreshMart Today 🏷️',
    message: 'Flat 20% OFF on fresh hydroponic greens & farm fruits. Apply coupon: FRESH20.',
    type: 'DEALS',
    isRead: true,
    timestamp: '1 hour ago',
  },
  {
    id: 'notif-4',
    title: 'Back in Stock Alert ⚡',
    message: 'Country Sourdough Bread 400g is back in stock at Bakehouse Artisan Bakery.',
    type: 'WISHLIST',
    isRead: true,
    timestamp: '3 hours ago',
  },
  {
    id: 'notif-5',
    title: 'Order Delivered Successfully ✅',
    message: 'Order #SZ-8890 was safely delivered to Home • Jaipur. Rate your experience!',
    type: 'ORDER',
    isRead: true,
    timestamp: 'Yesterday',
  },
  {
    id: 'notif-6',
    title: 'Cashback Credited 💰',
    message: '₹50 cashback credited to your SevaZo wallet from your weekend shopping reward.',
    type: 'ACCOUNT',
    isRead: true,
    timestamp: '2 days ago',
  },
];
export const mockSupportTickets: SupportTicket[] = [];

