import {
  CustomerUser,
  Category,
  Store,
  Product,
  Review,
  Address,
  Coupon,
  Order,
  LiveTrackingData,
  WalletTransaction,
  NotificationItem,
  SupportTicket,
} from '../types';

export const mockCustomer: CustomerUser = {
  id: 'cust-101',
  name: 'Aarav Sharma',
  phone: '+91 9876543210',
  email: 'aarav.sharma@example.com',
  avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150',
  isVerified: true,
  totalSpent: 12450,
  ordersCount: 18,
  walletBalance: 450,
  loyaltyTier: 'GOLD',
  createdAt: '2025-10-12T00:00:00Z',
};

export const mockBanners = [
  {
    id: 'ban-1',
    title: 'Super Flash Sale',
    subtitle: 'Flat 50% OFF on Fresh Grocery',
    tag: 'LIMITED TIME',
    imageUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=800',
    bgColor: '#059669',
  },
  {
    id: 'ban-2',
    title: 'Farm Fresh Organic Veggies',
    subtitle: 'Harvested Today, At Your Doorstep in 15 Mins',
    tag: 'FARM DIRECT',
    imageUrl: 'https://images.unsplash.com/photo-1610348725531-843dff563e2c?w=800',
    bgColor: '#16A34A',
  },
  {
    id: 'ban-3',
    title: 'Weekend Snack Mania',
    subtitle: 'Buy 1 Get 1 Free on Artisan Munchies',
    tag: 'PARTY PACK',
    imageUrl: 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=800',
    bgColor: '#D97706',
  },
];

export const mockCategories: Category[] = [
  {
    id: 'cat-1',
    name: 'Fruits & Veggies',
    slug: 'fruits-vegetables',
    imageUrl: 'https://images.unsplash.com/photo-1610348725531-843dff563e2c?w=300',
    itemCount: 84,
    subcategories: [
      { id: 'sub-11', name: 'Fresh Vegetables', slug: 'fresh-vegetables' },
      { id: 'sub-12', name: 'Fresh Fruits', slug: 'fresh-fruits' },
      { id: 'sub-13', name: 'Organic & Hydroponic', slug: 'organic' },
      { id: 'sub-14', name: 'Exotic Cuts', slug: 'exotics' },
    ],
  },
  {
    id: 'cat-2',
    name: 'Dairy & Breakfast',
    slug: 'dairy-breakfast',
    imageUrl: 'https://images.unsplash.com/photo-1528750997573-59b89d56f4f7?w=300',
    itemCount: 62,
    subcategories: [
      { id: 'sub-21', name: 'Milk & Paneer', slug: 'milk-paneer' },
      { id: 'sub-22', name: 'Bread & Pav', slug: 'bread' },
      { id: 'sub-23', name: 'Eggs & Cereals', slug: 'eggs-cereals' },
      { id: 'sub-24', name: 'Butter & Cheese', slug: 'butter-cheese' },
    ],
  },
  {
    id: 'cat-3',
    name: 'Munchies & Snacks',
    slug: 'snacks-munchies',
    imageUrl: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=300',
    itemCount: 110,
    subcategories: [
      { id: 'sub-31', name: 'Chips & Crisps', slug: 'chips' },
      { id: 'sub-32', name: 'Biscuits & Cookies', slug: 'biscuits' },
      { id: 'sub-33', name: 'Namkeen & Mixtures', slug: 'namkeen' },
      { id: 'sub-34', name: 'Chocolates & Candies', slug: 'chocolates' },
    ],
  },
  {
    id: 'cat-4',
    name: 'Cold Drinks & Juices',
    slug: 'cold-drinks-juices',
    imageUrl: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=300',
    itemCount: 45,
    subcategories: [
      { id: 'sub-41', name: 'Soft Drinks & Sodas', slug: 'soft-drinks' },
      { id: 'sub-42', name: 'Fresh Cold Pressed Juices', slug: 'juices' },
      { id: 'sub-43', name: 'Energy & Health Drinks', slug: 'energy-drinks' },
    ],
  },
  {
    id: 'cat-5',
    name: 'Instant Food',
    slug: 'instant-food',
    imageUrl: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?w=300',
    itemCount: 50,
    subcategories: [
      { id: 'sub-51', name: 'Noodles & Pasta', slug: 'noodles' },
      { id: 'sub-52', name: 'Ready To Cook Kits', slug: 'ready-to-cook' },
      { id: 'sub-53', name: 'Frozen Gourmet', slug: 'frozen' },
    ],
  },
  {
    id: 'cat-6',
    name: 'Personal Care',
    slug: 'personal-care',
    imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=300',
    itemCount: 95,
    subcategories: [
      { id: 'sub-61', name: 'Skin Care & Sunscreen', slug: 'skincare' },
      { id: 'sub-62', name: 'Hair Care & Shampoos', slug: 'haircare' },
      { id: 'sub-63', name: 'Oral Care', slug: 'oralcare' },
    ],
  },
  {
    id: 'cat-7',
    name: 'Pharmacy & Wellness',
    slug: 'pharmacy',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=300',
    itemCount: 70,
    subcategories: [
      { id: 'sub-71', name: 'Pain Relief & First Aid', slug: 'first-aid' },
      { id: 'sub-72', name: 'Vitamins & Supplements', slug: 'vitamins' },
    ],
  },
  {
    id: 'cat-8',
    name: 'Home & Kitchen',
    slug: 'home-kitchen',
    imageUrl: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=300',
    itemCount: 88,
    subcategories: [
      { id: 'sub-81', name: 'Cleaning & Detergents', slug: 'cleaning' },
      { id: 'sub-82', name: 'Kitchen Essentials', slug: 'kitchen' },
    ],
  },
];

export const mockStores: Store[] = [
  {
    id: 'store-1',
    businessName: 'SevaZo Supermart Express',
    ownerName: 'Vikas Agarwal',
    avatar: 'https://images.unsplash.com/photo-1534723452862-4c874018d66d?w=200',
    coverImage: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=800',
    rating: 4.9,
    reviewsCount: 1420,
    deliveryTime: '10-15 mins',
    distanceKm: 0.8,
    address: 'Plot 44, 100ft Road, Indiranagar',
    city: 'Bengaluru',
    isOpen: true,
    tags: ['Supermarket', 'Fresh Veggies', 'Fastest Delivery'],
    bannerText: '⚡ Express 12 Min Delivery Hub',
  },
  {
    id: 'store-2',
    businessName: 'Nature Fresh Organic Store',
    ownerName: 'Sunita Rao',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200',
    coverImage: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=800',
    rating: 4.8,
    reviewsCount: 680,
    deliveryTime: '15-20 mins',
    distanceKm: 1.6,
    address: '12th Main, HAL 2nd Stage',
    city: 'Bengaluru',
    isOpen: true,
    tags: ['Certified Organic', 'Chemical Free', 'Farm Direct'],
    bannerText: '🌱 100% Pesticide Free Certified',
  },
  {
    id: 'store-3',
    businessName: 'Gourmet Artisans Bakery & Dairy',
    ownerName: 'Chef Rohit Sengupta',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200',
    coverImage: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800',
    rating: 4.9,
    reviewsCount: 920,
    deliveryTime: '20-25 mins',
    distanceKm: 2.3,
    address: '5th Block, Koramangala',
    city: 'Bengaluru',
    isOpen: true,
    tags: ['Artisan Bread', 'Sourdough', 'A2 Milk', 'Bakes'],
    bannerText: '🥖 Freshly Baked Every Morning at 6 AM',
  },
  {
    id: 'store-4',
    businessName: 'Apollo MedPlus 24x7 Pharmacy',
    ownerName: 'Dr. Ramesh Kumar',
    avatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=200',
    coverImage: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800',
    rating: 4.7,
    reviewsCount: 450,
    deliveryTime: '15-20 mins',
    distanceKm: 1.1,
    address: 'CMH Road, Indiranagar',
    city: 'Bengaluru',
    isOpen: true,
    tags: ['Pharmacy', 'Medicines', 'Health & Wellness'],
    bannerText: '💊 24/7 Verified Pharmacist on Duty',
  },
];

export const mockProducts: Product[] = [
  {
    id: 'prod-1',
    name: 'Fresh Hydroponic English Spinach (Palak)',
    slug: 'hydroponic-spinach-250g',
    description: 'Crisp, triple-washed pesticide-free hydroponic baby spinach leaves packed with iron and vital minerals.',
    categoryId: 'cat-1',
    categoryName: 'Fruits & Veggies',
    vendorId: 'store-1',
    storeId: 'store-1',
    storeName: 'SevaZo Supermart Express',
    price: 38,
    compareAtPrice: 55,
    discountPercent: 30,
    stock: 45,
    unit: '250 g',
    rating: 4.8,
    reviewsCount: 234,
    images: [
      'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=600',
      'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600',
    ],
    variants: [
      { id: 'v-1', productId: 'prod-1', name: '250 g', sku: 'SPN-250', price: 38, compareAtPrice: 55, stock: 45 },
      { id: 'v-2', productId: 'prod-1', name: '500 g', sku: 'SPN-500', price: 68, compareAtPrice: 100, stock: 20 },
    ],
    tags: ['Hydroponic', 'Organic', 'Best Seller'],
    isFeatured: true,
    isTrending: true,
    inStock: true,
  },
  {
    id: 'prod-2',
    name: 'Amul Taaza Homogenised Toned Milk',
    slug: 'amul-taaza-milk-1l',
    description: 'Pasteurised toned milk with 3.0% fat and 8.5% SNF. Wholesome and nutritious for daily tea, coffee, and shakes.',
    categoryId: 'cat-2',
    categoryName: 'Dairy & Breakfast',
    vendorId: 'store-1',
    storeId: 'store-1',
    storeName: 'SevaZo Supermart Express',
    price: 54,
    compareAtPrice: 56,
    discountPercent: 4,
    stock: 120,
    unit: '1 Litre',
    rating: 4.9,
    reviewsCount: 890,
    images: [
      'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=600',
      'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=600',
    ],
    variants: [
      { id: 'v-3', productId: 'prod-2', name: '500 ml', sku: 'MILK-500', price: 28, compareAtPrice: 28, stock: 80 },
      { id: 'v-4', productId: 'prod-2', name: '1 Litre', sku: 'MILK-1L', price: 54, compareAtPrice: 56, stock: 120 },
    ],
    tags: ['Daily Need', 'Dairy', 'Must Have'],
    isFeatured: true,
    isTrending: true,
    inStock: true,
  },
  {
    id: 'prod-3',
    name: 'Kashmiri Royal Gala Apples (Sweet & Crunchy)',
    slug: 'kashmiri-royal-gala-apples-4pcs',
    description: 'Hand-picked premium grade Kashmiri Royal Gala apples known for their juicy texture and natural sweetness.',
    categoryId: 'cat-1',
    categoryName: 'Fruits & Veggies',
    vendorId: 'store-2',
    storeId: 'store-2',
    storeName: 'Nature Fresh Organic Store',
    price: 149,
    compareAtPrice: 199,
    discountPercent: 25,
    stock: 30,
    unit: '4 pcs (approx 600g)',
    rating: 4.7,
    reviewsCount: 156,
    images: [
      'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=600',
      'https://images.unsplash.com/photo-1570913149827-d2ac84ab3f9a?w=600',
    ],
    tags: ['Kashmiri', 'Fresh Fruits', 'Sweet'],
    isFeatured: true,
    isTrending: false,
    inStock: true,
  },
  {
    id: 'prod-4',
    name: 'Epigamia Greek Yogurt (Wild Blueberry)',
    slug: 'epigamia-greek-yogurt-blueberry-100g',
    description: 'High protein Greek yogurt with real wild blueberry compote. Zero preservatives and rich in probiotics.',
    categoryId: 'cat-2',
    categoryName: 'Dairy & Breakfast',
    vendorId: 'store-3',
    storeId: 'store-3',
    storeName: 'Gourmet Artisans Bakery & Dairy',
    price: 55,
    compareAtPrice: 60,
    discountPercent: 8,
    stock: 25,
    unit: '100 g cup',
    rating: 4.8,
    reviewsCount: 310,
    images: [
      'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600',
    ],
    tags: ['Probiotic', 'High Protein', 'Gourmet'],
    isFeatured: false,
    isTrending: true,
    inStock: true,
  },
  {
    id: 'prod-5',
    name: 'Artisan Country Sourdough Loaf (Slow Fermented)',
    slug: 'artisan-sourdough-loaf',
    description: 'Baked fresh with a 36-hour slow fermented levain, golden crust, and airy tender crumb.',
    categoryId: 'cat-2',
    categoryName: 'Dairy & Breakfast',
    vendorId: 'store-3',
    storeId: 'store-3',
    storeName: 'Gourmet Artisans Bakery & Dairy',
    price: 130,
    compareAtPrice: 160,
    discountPercent: 18,
    stock: 15,
    unit: '400 g Loaf',
    rating: 4.9,
    reviewsCount: 142,
    images: [
      'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600',
    ],
    tags: ['Artisan Bakery', 'No Chemicals', 'Chef Pick'],
    isFeatured: true,
    isTrending: true,
    inStock: true,
  },
  {
    id: 'prod-6',
    name: 'Doritos Sweet Chilli Nacho Crisps',
    slug: 'doritos-sweet-chilli-crisps-80g',
    description: 'Bold crunch and tangy sweet chilli punch in every bite. Perfect for movie nights and snacking.',
    categoryId: 'cat-3',
    categoryName: 'Munchies & Snacks',
    vendorId: 'store-1',
    storeId: 'store-1',
    storeName: 'SevaZo Supermart Express',
    price: 35,
    compareAtPrice: 40,
    discountPercent: 12,
    stock: 60,
    unit: '80 g pack',
    rating: 4.6,
    reviewsCount: 420,
    images: [
      'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=600',
    ],
    tags: ['Snack Attack', 'Crunchy', 'Party'],
    isFeatured: false,
    isTrending: true,
    inStock: true,
  },
  {
    id: 'prod-7',
    name: 'Raw Pressery Cold Pressed Valencia Orange Juice',
    slug: 'raw-pressery-orange-juice-250ml',
    description: '100% pure Valencia orange juice. No added sugar, no concentrates, and never heat-treated.',
    categoryId: 'cat-4',
    categoryName: 'Cold Drinks & Juices',
    vendorId: 'store-1',
    storeId: 'store-1',
    storeName: 'SevaZo Supermart Express',
    price: 85,
    compareAtPrice: 99,
    discountPercent: 14,
    stock: 35,
    unit: '250 ml bottle',
    rating: 4.7,
    reviewsCount: 180,
    images: [
      'https://images.unsplash.com/photo-1613478223719-2ab802602423?w=600',
    ],
    tags: ['Cold Pressed', 'No Sugar', 'Immunity'],
    isFeatured: true,
    isTrending: false,
    inStock: true,
  },
  {
    id: 'prod-8',
    name: 'Himalaya Purifying Neem Face Wash',
    slug: 'himalaya-neem-face-wash-150ml',
    description: 'Enriched with neem and turmeric to combat acne, purify pores, and leave skin clear and refreshed.',
    categoryId: 'cat-6',
    categoryName: 'Personal Care',
    vendorId: 'store-4',
    storeId: 'store-4',
    storeName: 'Apollo MedPlus 24x7 Pharmacy',
    price: 180,
    compareAtPrice: 220,
    discountPercent: 18,
    stock: 40,
    unit: '150 ml tube',
    rating: 4.8,
    reviewsCount: 560,
    images: [
      'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600',
    ],
    tags: ['Skin Care', 'Herbal', 'Top Rated'],
    isFeatured: false,
    isTrending: false,
    inStock: true,
  },
];

export const mockReviews: Review[] = [
  {
    id: 'rev-1',
    productId: 'prod-1',
    customerId: 'cust-201',
    customerName: 'Pooja Hegde',
    customerAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100',
    rating: 5,
    comment: 'Incredible freshness! Received within 11 minutes and the leaves were so crisp and tender.',
    verifiedPurchase: true,
    createdAt: '2 days ago',
    likesCount: 14,
  },
  {
    id: 'rev-2',
    productId: 'prod-1',
    customerId: 'cust-202',
    customerName: 'Rohan Deshmukh',
    customerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100',
    rating: 5,
    comment: 'Way better than local vendor spinach. Completely dirt-free and washed properly.',
    verifiedPurchase: true,
    createdAt: '1 week ago',
    likesCount: 9,
  },
  {
    id: 'rev-3',
    productId: 'prod-1',
    customerId: 'cust-203',
    customerName: 'Kavita Nair',
    rating: 4,
    comment: 'Good quality baby spinach, slightly on the premium price side but worth the speed.',
    verifiedPurchase: true,
    createdAt: '2 weeks ago',
    likesCount: 3,
  },
];

export const mockAddresses: Address[] = [
  {
    id: 'addr-1',
    customerId: 'cust-101',
    label: 'Home',
    line1: 'Flat 402, Green Glen Heights, 12th Main',
    line2: 'HAL 2nd Stage, Indiranagar',
    landmark: 'Near Starbucks & Toit Brewpub',
    city: 'Bengaluru',
    state: 'Karnataka',
    pincode: '560038',
    latitude: 12.9716,
    longitude: 77.6412,
    isDefault: true,
    contactName: 'Aarav Sharma',
    contactPhone: '+91 9876543210',
  },
  {
    id: 'addr-2',
    customerId: 'cust-101',
    label: 'Work',
    line1: 'Tower B, 5th Floor, WeWork Prestige Tech Park',
    line2: 'Marathahalli - Sarjapur Outer Ring Road',
    landmark: 'Kadubeesanahalli Junction',
    city: 'Bengaluru',
    state: 'Karnataka',
    pincode: '560103',
    latitude: 12.9352,
    longitude: 77.6946,
    isDefault: false,
    contactName: 'Aarav Sharma',
    contactPhone: '+91 9876543210',
  },
];

export const mockCoupons: Coupon[] = [
  {
    id: 'c-1',
    code: 'SEVAZO50',
    description: 'Flat 50% OFF up to ₹100 on orders above ₹199',
    discountType: 'PERCENTAGE',
    discountValue: 50,
    minOrderAmount: 199,
    maxDiscount: 100,
    validUntil: '2026-12-31',
    isActive: true,
  },
  {
    id: 'c-2',
    code: 'FREESHIP',
    description: 'Zero Delivery Fee on orders above ₹149',
    discountType: 'FIXED',
    discountValue: 25,
    minOrderAmount: 149,
    validUntil: '2026-12-31',
    isActive: true,
  },
  {
    id: 'c-3',
    code: 'FARM100',
    description: 'Flat ₹100 OFF on Organic Fruits & Vegetables (Min ₹399)',
    discountType: 'FIXED',
    discountValue: 100,
    minOrderAmount: 399,
    validUntil: '2026-12-31',
    isActive: true,
  },
];

export const mockOrders: Order[] = [
  {
    id: 'ord-1001',
    orderNumber: 'SVZ-20260821-7892',
    createdAt: '2026-08-21T16:30:00Z',
    status: 'IN_TRANSIT',
    paymentStatus: 'PAID',
    paymentMethod: 'UPI',
    items: [
      {
        id: 'oi-1',
        productId: 'prod-1',
        productName: 'Fresh Hydroponic English Spinach (Palak)',
        productImage: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=200',
        variantName: '250 g',
        unitPrice: 38,
        quantity: 2,
        totalPrice: 76,
      },
      {
        id: 'oi-2',
        productId: 'prod-2',
        productName: 'Amul Taaza Homogenised Toned Milk',
        productImage: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=200',
        variantName: '1 Litre',
        unitPrice: 54,
        quantity: 1,
        totalPrice: 54,
      },
      {
        id: 'oi-3',
        productId: 'prod-7',
        productName: 'Raw Pressery Cold Pressed Valencia Orange Juice',
        productImage: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?w=200',
        variantName: '250 ml',
        unitPrice: 85,
        quantity: 1,
        totalPrice: 85,
      },
    ],
    subtotal: 215,
    deliveryFee: 15,
    tax: 8,
    discount: 50,
    totalAmount: 188,
    deliveryAddress: mockAddresses[0],
    store: {
      id: 'store-1',
      businessName: 'SevaZo Supermart Express',
      phone: '+91 80 4455 6677',
      address: 'Plot 44, 100ft Road, Indiranagar',
    },
    estimatedDeliveryTime: '17:02 (in 12 mins)',
    deliveryOtp: '8392',
    rider: {
      id: 'r-401',
      name: 'Santosh Rawat',
      phone: '+91 9123456780',
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
      rating: 4.9,
      vehicleNumber: 'KA-03-EM-8899',
      vehicleType: 'Electric Scooter',
    },
    canCancel: false,
    canReturn: false,
  },
  {
    id: 'ord-1002',
    orderNumber: 'SVZ-20260819-4411',
    createdAt: '2026-08-19T09:15:00Z',
    status: 'DELIVERED',
    paymentStatus: 'PAID',
    paymentMethod: 'UPI',
    items: [
      {
        id: 'oi-4',
        productId: 'prod-5',
        productName: 'Artisan Country Sourdough Loaf',
        productImage: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=200',
        unitPrice: 130,
        quantity: 1,
        totalPrice: 130,
      },
      {
        id: 'oi-5',
        productId: 'prod-4',
        productName: 'Epigamia Greek Yogurt (Wild Blueberry)',
        productImage: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=200',
        unitPrice: 55,
        quantity: 2,
        totalPrice: 110,
      },
    ],
    subtotal: 240,
    deliveryFee: 0,
    tax: 12,
    discount: 25,
    totalAmount: 227,
    deliveryAddress: mockAddresses[0],
    store: {
      id: 'store-3',
      businessName: 'Gourmet Artisans Bakery & Dairy',
      address: '5th Block, Koramangala',
    },
    deliveredAt: '19 Aug 2026, 09:33 AM',
    canCancel: false,
    canReturn: true,
  },
];

export const mockLiveTracking: LiveTrackingData = {
  orderId: 'ord-1001',
  orderNumber: 'SVZ-20260821-7892',
  status: 'IN_TRANSIT',
  estimatedDeliveryTime: '5:02 PM',
  remainingMinutes: 11,
  distanceRemainingKm: 1.4,
  rider: {
    id: 'r-401',
    name: 'Santosh Rawat',
    phone: '+91 9123456780',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
    rating: 4.9,
    vehicleModel: 'Ather 450X (Electric)',
    vehiclePlate: 'KA-03-EM-8899',
    currentLat: 12.9755,
    currentLng: 77.6380,
  },
  storeLocation: {
    name: 'SevaZo Supermart Express',
    latitude: 12.9784,
    longitude: 77.6408,
  },
  deliveryLocation: {
    address: 'Flat 402, Green Glen Heights, Indiranagar',
    latitude: 12.9716,
    longitude: 77.6412,
  },
  timeline: [
    {
      step: 'PLACED',
      title: 'Order Placed',
      description: 'Received by SevaZo Express Hub',
      timestamp: '4:48 PM',
      completed: true,
      current: false,
    },
    {
      step: 'CONFIRMED',
      title: 'Order Confirmed',
      description: 'Store accepted and bag assigned',
      timestamp: '4:49 PM',
      completed: true,
      current: false,
    },
    {
      step: 'PREPARING',
      title: 'Packed & Quality Checked',
      description: 'Fresh items chilled and bagged',
      timestamp: '4:52 PM',
      completed: true,
      current: false,
    },
    {
      step: 'IN_TRANSIT',
      title: 'Out for Delivery',
      description: 'Santosh is on the way on Ather 450X',
      timestamp: '4:55 PM',
      completed: false,
      current: true,
    },
    {
      step: 'DELIVERED',
      title: 'Delivered at Doorstep',
      description: 'Handover with OTP verification',
      timestamp: 'Est. 5:02 PM',
      completed: false,
      current: false,
    },
  ],
};

export const mockWalletTransactions: WalletTransaction[] = [
  {
    id: 'tx-1',
    type: 'CREDIT',
    title: 'Cashback Reward',
    description: 'Order SVZ-20260819-4411 Cashback',
    amount: 50,
    balanceAfter: 450,
    referenceId: 'SVZ-20260819-4411',
    createdAt: '19 Aug 2026, 09:35 AM',
  },
  {
    id: 'tx-2',
    type: 'CREDIT',
    title: 'Added to Wallet',
    description: 'UPI Top-Up via Google Pay',
    amount: 500,
    balanceAfter: 400,
    createdAt: '15 Aug 2026, 02:10 PM',
  },
  {
    id: 'tx-3',
    type: 'DEBIT',
    title: 'Paid for Order',
    description: 'SevaZo Grocery Order',
    amount: 100,
    balanceAfter: -100,
    referenceId: 'SVZ-20260815-1102',
    createdAt: '15 Aug 2026, 02:15 PM',
  },
];

export const mockNotifications: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'Rider is arriving soon! 🛵',
    message: 'Santosh Rawat is 3 minutes away with your SevaZo order.',
    type: 'DELIVERY',
    isRead: false,
    timestamp: 'Just now',
  },
  {
    id: 'notif-2',
    title: '⚡ Weekend Flash Sale Live!',
    message: 'Use code SEVAZO50 to get flat 50% OFF on all fresh fruits & veggies.',
    type: 'PROMO',
    isRead: false,
    timestamp: '2 hours ago',
  },
  {
    id: 'notif-3',
    title: 'Order Delivered Successfully ✅',
    message: 'Your order SVZ-20260819-4411 was delivered. Rate your items!',
    type: 'ORDER',
    isRead: true,
    timestamp: '2 days ago',
  },
];

export const mockSupportTickets: SupportTicket[] = [
  {
    id: 'tkt-1',
    ticketNumber: 'TKT-9941',
    subject: 'Packaging feedback for fresh bakery loaf',
    status: 'RESOLVED',
    priority: 'LOW',
    createdAt: '19 Aug 2026',
    updatedAt: '19 Aug 2026',
    lastMessage: 'Thank you for your feedback! We have updated the bakery packaging.',
  },
];
